# Generated by Django 3.1.3 on 2020-12-03 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201204_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cooment_text',
            field=models.TextField(verbose_name='Comment'),
        ),
    ]
