# Generated by Django 3.1.3 on 2020-12-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_likedislike'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='headline',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
